server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          messaging-client-oidc:
            provider: keycloak
            client-id: messaging-client
            client-secret: TsI7rK5vVmD7tzNgbhtxnpQVx6y9LqNS
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile
            client-name: messaging-client-oidc
          messaging-client-authorization-code:
            provider: keycloak
            client-id: messaging-client
            client-secret: TsI7rK5vVmD7tzNgbhtxnpQVx6y9LqNS
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/authorized"
            scope: message.read,message.write
            client-name: messaging-client-authorization-code
          messaging-client-client-credentials:
            provider: keycloak
            client-id: messaging-client
            client-secret: TsI7rK5vVmD7tzNgbhtxnpQVx6y9LqNS
            authorization-grant-type: client_credentials
            scope: message.read,message.write
#            client-name: messaging-client-client-credentials
        provider:
          keycloak:
            issuer-uri: http://localhost:8180/realms/spring-as

messages:
  base-uri: http://127.0.0.1:8090/messages
