server:
  port: 8086

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false

messages:
  base-uri: http://127.0.0.1:8080/safeguard/api/v1/settings/global
#  base-uri: http://127.0.0.1:8080/safeguard/api/v1/channels

### For empty value of token-uri below, no token will be created explicitly ###
token-uri:
client-id:
client-secret:

#token-uri: http://127.0.0.1:8080/safeguard/api/oauth/token

### Explict token for Auth0 ###
#token-uri: https://gsah-mbp.us.auth0.com/oauth/token
#client-id: ed0Cjk2m8vKJKuwan57OtwqWtQXlxqi5
#client-secret: 4ZCW6ikNc35DEoJO1XjFw3Km2zQZhyUzBIQOU6OIdxR6iiFRxPFsGQ2zAMFlBghd

### Explict token for Keycloak ###
#token-uri: http://127.0.0.1:8180/realms/master/protocol/openid-connect/token
#client-id: messaging-client
#client-secret: pWXfiOeieGErbZFSOeaeJa8b8maBikwq

### Explict token for Spring AS ###
#token-uri: http://127.0.0.1:9000/oauth2/token
#client-id: safeguard-client
#client-secret: safeguardSecret

