server:
  port: 8086

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
#    org.springframework.boot.autoconfigure: DEBUG

spring:
  thymeleaf:
    cache: false

messages:
  base-uri: http://127.0.0.1:8080/safeguard/api/v1/settings/global
#  base-uri: http://127.0.0.1:8080/safeguard/api/v1/channels

### For empty value of token-uri below, no token will be created explicitly ###

sgc:
  token-uri: http://127.0.0.1:8080/safeguard/api/oauth/token

auth0:
  token-uri: https://gsah-mbp.us.auth0.com/oauth/token
  client-id: oCSO8PBNyYqUYJylcuufC6NqEpPc1Zjc
  client-secret: E2XKWE9dU0NGVNyj4S4cPuPhN_v5KT3jBLb4FUYtXXRo7H8SPLK6vHG8MecFK1Ya

keycloak:
  token-uri: http://127.0.0.1:8180/realms/master/protocol/openid-connect/token
  client-id: messaging-client
  client-secret: pWXfiOeieGErbZFSOeaeJa8b8maBikwq

spring-as:
  token-uri: http://127.0.0.1:9000/oauth2/token
  client-id: safeguard-client
  client-secret: safeguardSecret

### Comment out line below if setting non-empty values for this
token-uri:

#token-uri: ${sgc.token-uri}

### Uncomment below for Auth0 ###
#token-uri: ${auth0.token-uri}
client-id: ${auth0.client-id}
client-secret: ${auth0.client-secret}

### Uncomment below for keycloak ###
#token-uri: ${keycloak.token-uri}
#client-id: ${keycloak.client-id}
#client-secret: ${keycloak.client-secret}

### Uncomment below for Spring AS ###
#token-uri: ${spring-as.token-uri}
#client-id: ${spring-as.client-id}
#client-secret: ${spring-as.client-secret}
